### ISSUE TITLE
创建数据库表的脚本有吗？报错，

### ISSUE THREAD

**Issue by bi7jta** [BruceQiu1996/Socks5Proxy4Net#1]
可否提供下，谢谢！

**Comment by BruceQiu1996** [comment]
EFCore学习下如何使用code first还原数据库，需要在data目录下有一个data.db这个sqlite数据库

**Comment by typetrade** [comment]
@bi7jta 你设置一下data.db，复制到输出目录即可

--
-- File generated with SQLiteStudio v3.4.4 on 周日 8月 11 16:35:52 2024
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: __EFMigrationsHistory
DROP TABLE IF EXISTS __EFMigrationsHistory;
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (

    "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY,

    "ProductVersion" TEXT NOT NULL

);
INSERT INTO __EFMigrationsHistory (MigrationId, ProductVersion) VALUES ('20230514084552_InitDatabase', '7.0.5');
INSERT INTO __EFMigrationsHistory (MigrationId, ProductVersion) VALUES ('20230514085303_AddAdminAccount', '7.0.5');

-- Table: Users
DROP TABLE IF EXISTS Users;
CREATE TABLE IF NOT EXISTS "Users" (

    "Id" TEXT NOT NULL CONSTRAINT "PK_Users" PRIMARY KEY,

    "UserName" TEXT NULL,

    "Password" TEXT NULL,

    "ExpireTime" TEXT NOT NULL,

    "UploadBytes" INTEGER NOT NULL,

    "DownloadBytes" INTEGER NOT NULL,

    "Role" INTEGER NOT NULL

);
INSERT INTO Users (Id, UserName, Password, ExpireTime, UploadBytes, DownloadBytes, Role) VALUES ('1ce5a888-d236-4e0b-9a65-5adbcfd2baf8', 'Admin', '123456', '9999-12-31 23:59:59.9999999', 134421, 393364, 99);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;

**Comment by bi7jta** [comment]
收到，已经解决，非常感谢！



steven ***@***.***> 于2024年8月11日周日 16:46写道：
